version: '3.4'
services:
  backend:
    container_name: bunnyshell-books-backend
    build:
      context: ./backend
      target: ${FRONTEND_BUILD_TARGET:-dev} # use "prod" for production
    volumes:
       - ./backend:/usr/src/app/backend
    environment:
      - CLAU.VAR=bla
      - CLAU.VAR.SUBVAR=blabla
      - CLAU.VAR.SUBVAR.SUBSUBVAR=blablabla
      - node.name=es01
      - cluster.name=CLUSTER_NAME
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - POSTGRES_HOST=db # name of the "db" service
      - POSTGRES_DB=bunny_books
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=need-to-replace
      - FRONTEND_URL=${FRONTEND_URL-http://books.local.bunnyshell.com:8080}
    ports:
      - "3080:3080"
    depends_on:
      - db
  db:
    container_name: bunnyshell-books-db
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bunny_books
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=need-to-replace
    expose:
      - 5432
  frontend:
      container_name: bunnyshell-books-frontend
      build:
        context: ./frontend
        target: ${FRONTEND_BUILD_TARGET:-dev} # use "prod" for production
        args:
          REACT_APP_BASE_API: ${BACKEND_URL-http://books-api.local.bunnyshell.com:3080}
      volumes:
        - ./frontend:/var/www/frontend:delegated
      ports:
        - "8080:8080"

volumes:
  db-data:
