version: '3.4'
services:
  backend:
    container_name: bunnyshell-books-backend
    build:
      context: ./backend
      target: ${BACKEND_BUILD_TARGET:-prod} # use "dev" for development
    volumes:
       - ./backend:/usr/src/app/backend
    environment:
      - POSTGRES_HOST=db # name of the "db" service
      - POSTGRES_DB=bunny_books
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=need-to-replace
      - FRONTEND_URL=${FRONTEND_URL:-https://{{ components.frontend.ingress.hosts[0] }}}
    ports:
      - "3080:3080"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bunny_books
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=need-to-replace
    expose:
      - 5432
  frontend:
      container_name: bunnyshell-books-frontend
      build:
        context: ./frontend
        target: ${FRONTEND_BUILD_TARGET:-prod} # use "dev" for development
        args:
          REACT_APP_APP_URL: ${FRONTEND_URL:-https://{{ components.frontend.ingress.hosts[0] }}}
          REACT_APP_BASE_API: ${BACKEND_URL:-https://{{ components.backend.ingress.hosts[0] }}}
      environment:
        # reverse proxy vars
        - VIRTUAL_HOST=${FRONTEND_VIRTUAL_HOST:-https://{{ components.frontend.ingress.hosts[0] }}}
        - VIRTUAL_PORT=8080
      volumes:
        - ./frontend:/var/www/frontend:delegated
      ports:
        - "80:8080"   # for production mode
        - "8081:8081" # for development mode

volumes:
  db-data: